[theme]
primaryColor = "#168CE3"
backgroundColor = "#061A2D"
secondaryBackgroundColor = "#0D2B46"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
