[theme]
primaryColor = "#372580"
backgroundColor = "#F3F3F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#18181B"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
